#!/usr/bin/env ruby

def merge(left, right)

  ans=[]
  until (left.empty? || right.empty?)
    if (right.first < left.first)
      ans.push(right.shift())
    else
      ans.push(left.shift())
    end
  end

  ans + left + right
end




arr=ARGV.join(' ').split('l')
puts "______________________"
puts "left"
puts left=arr[0].split(' ')
puts "______________"
puts right =  arr[1].split(' ')
puts "right"
puts "_____________________"
sortedarr=merge( left, right)

system( "echo #{sortedarr.join(' ')}" )
