#!/bin/bash


numss=$( ./randomnums $1)
nums=(${numss// / })
runstuff(){
mp="${#nums[@]}/2"
left[left]="${nums[@]:0:${mp}}"
right[right]="${nums[@]:${mp}:${#nums[@]}}"

#echo ${left[l]}
#echo ${right[r]}
#echo
left[l]=$( ./multimerge ${left[@]} )
right[r]=$( ./multimerge ${right[@]} )
#echo
#echo ${left[l]}
#echo ${right[r]}

#left[l]=$( ./multimerge ${left[@]} )
#right[r]=$( ./multimerge ${right[@]} )
left+=l

#echo ${left[l]}
#echo
#echo ${right[r]}

wait
echo $(./merge ${left[l]} ${right[r]})

}
time runstuff
