#!/bin/bash    
sorta () {
	arr=("$@")
	if [ "${#arr[@]}" -lt 2 ]
	then 
		echo ${arr[@]}
		return ${arr[1]}
	fi
	pivot="${arr[0]}"
	for ((i=1; i <= "${#arr[@]}"; ++i))
    	do
		#echo ${arr[i]}
		if [[ ${arr[i]} < pivot ]]
		then
			local left+=${arr[i]}
		else
			local right+=${arr[i]}
		fi
		
    	done
	left=`sorta ${left[@]}`
	right=`sorta ${right[@]}`
    	ans=(${left[@]} ${pivot} ${right[@]})
    	echo ${ans[@]}
    	return 1
	

}

sortb () {
	echo ${arr[@]}
}
# arr=(6 5 68 43 82 60 45 19 78 95)
#arr[0]=0
for i in {0..10}; do 
	arr[i]=$(($RANDOM%100))
done
echo ${arr[@]}
 echo 
 echo `sorta ${arr[*]}`
echo 
echo ${arr[@]}

    
#command > "${tmp1}" & 
#command > "${tmp2}" & 
#wait
#cat "${tmp1}" "${tmp2}" >> "${main}"
#rm -f "${tmp1}" "${tmp2}"
